import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const msSans = localFont({
  src: [
    {
      path: "ms_sans_serif.woff",
      weight: "normal",
      style: "normal",
    },
    {
      path: "MS Sans Serif Bold.ttf",
      weight: "bold",
      style: "normal",
    },
  ],
  variable: "--font-msSans",
});

export const trebuchet = localFont({
  src: [
    {
      path: "trebuc.ttf",
      weight: "bold",
      style: "normal",
    },
  ],
  variable: "--font-trebuchet",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${trebuchet.className} ${msSans.className}`}>
        {children}
      </body>
    </html>
  );
}
